kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: devopsbatches.trainwithkunal.com
spec:
  group: trainwithkunal.com
  names:
    plural: devopsbatches
    singular: devopsbatch
    kind: DevOpsBatch
    shortNames:
     - kunal
     - kid
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema: 
     openAPIV3Schema:
       type: object
       properties: 
        spec:
          type: object
          properties:
            name: 
              type: string
              description: "This is created by Kunal Dugar"
            duration:
              type: string
              description: "This is duration of the devops batch"
            mode:
              type: string
              description: "This is mode of the devops batch"
            platform:
              type: string
              description: "This is platform of the devops batch"