kind: Deployment
apiVersion: apps/v1
metadata:
  name: notes-app-deployment
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata: 
      name: notes-app-pod
      labels:
        app: notes-app
    spec:
      containers:
        - name: notes-app
          image: kunal245/nptes-app-k8s:latest
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /
              port: 8000
          readinessProbe:
            httpGet:
             path: /
             port: 8000
