apiVersion: apps/v1
kind: Deployment
metadata:
  name: archer
  namespace: archer
  labels:
    kubernetes.io/workload.name: archer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
