apiVersion: apps/v1
kind: Deployment
metadata:
  name: jofra
  namespace: jofra
  labels:
    kubernetes.io/metadata.name: jofra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
