kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apache-manager
  namespace: apache
rules:
  - apiGroups: ["*"] #, "apps/v1", "rbac.authorization.k8s.io", "batch"]
    resources: ["pods"] #deployments", "pods", "services"]
    verbs: ["get"] #  "get", "apply", "watch", "create", "patch", "delete"]